spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: secret #JWT加解密使用的密钥
  expiration: 3600 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头
